export const forumCategories = {
  GAIALAND: {
    title: "GAIALAND",
    description: "Centro oficial de información del servidor",
    color: "purple.500",
    icon: "🎮",
    subcategories: [
      {
        id: "novedades",
        title: "NOVEDADES",
        description: "Últimas novedades del servidor",
        posts: [
          {
            id: 1,
            title: "¡Nuevo sistema de rangos disponible!",
            author: "AdminGaia",
            replies: 23,
            views: 456,
            lastActivity: "hace 2 horas",
            pinned: true,
            tags: ["importante", "sistema", "rangos"],
          },
          {
            id: 2,
            title: "Evento especial de Halloween 2024",
            author: "ModeradorX",
            replies: 45,
            views: 892,
            lastActivity: "hace 5 horas",
            pinned: false,
            tags: ["evento", "halloween", "recompensas"],
          },
          {
            id: 3,
            title: "Evento especial de Halloween 2024",
            author: "ModeradorX",
            replies: 45,
            views: 892,
            lastActivity: "hace 5 horas",
            pinned: false,
            tags: ["evento", "halloween", "recompensas"],
          },
          {
            id: 4,
            title: "Evento especial de Halloween 2024",
            author: "ModeradorX",
            replies: 45,
            views: 892,
            lastActivity: "hace 5 horas",
            pinned: false,
            tags: ["evento", "halloween", "recompensas"],
          },
          {
            id: 5,
            title: "Evento especial de Halloween 2024",
            author: "ModeradorX",
            replies: 45,
            views: 892,
            lastActivity: "hace 5 horas",
            pinned: false,
            tags: ["evento", "halloween", "recompensas"],
          },
          {
            id: 6,
            title: "Evento especial de Halloween 2024",
            author: "ModeradorX",
            replies: 45,
            views: 892,
            lastActivity: "hace 5 horas",
            pinned: false,
            tags: ["evento", "halloween", "recompensas"],
          },
          {
            id: 7,
            title: "Evento especial de Halloween 2024",
            author: "ModeradorX",
            replies: 45,
            views: 892,
            lastActivity: "hace 5 horas",
            pinned: false,
            tags: ["evento", "halloween", "recompensas"],
          },
          {
            id: 8,
            title: "Evento especial de Halloween 2024",
            author: "ModeradorX",
            replies: 45,
            views: 892,
            lastActivity: "hace 5 horas",
            pinned: false,
            tags: ["evento", "halloween", "recompensas"],
          },
        ],
      },
      {
        id: "actualizaciones",
        title: "ACTUALIZACIONES",
        description: "Parches y mejoras del servidor",
        posts: [
          {
            id: 9,
            title: "Parche 2.4.1 - Mejoras de rendimiento",
            author: "DevTeam",
            replies: 12,
            views: 234,
            lastActivity: "hace 1 día",
            pinned: false,
            tags: ["parche", "rendimiento", "bugfix"],
          },
        ],
      },
      {
        id: "eventos",
        title: "PRÓXIMOS EVENTOS",
        description: "Calendario de eventos comunidad",
        posts: [
          {
            id: 10,
            title: "Torneo PvP Mensual - Diciembre",
            author: "EventMaster",
            replies: 67,
            views: 1203,
            lastActivity: "hace 3 horas",
            pinned: true,
            tags: ["torneo", "pvp", "competitivo"],
          },
        ],
      },
      {
        id: "reglas",
        title: "REGLAS",
        description: "Normas y directrices del servidor",
        posts: [
          {
            id: 11,
            title: "Reglas del Servidor - Leer antes de jugar",
            author: "AdminGaia",
            replies: 3,
            views: 5678,
            lastActivity: "hace 1 semana",
            pinned: true,
            tags: ["reglas", "obligatorio", "normas"],
          },
        ],
      },
    ],
  },
  COMUNIDAD: {
    title: "COMUNIDAD",
    description: "Espacio para jugadores y creadores de contenido",
    color: "blue.500",
    icon: "👥",
    subcategories: [
      {
        id: "general",
        title: "GENERAL",
        description: "Discusiones generales de la comunidad",
        posts: [
          {
            id: 6,
            title: "¿Cuál es tu build favorita para PvE?",
            author: "Player123",
            replies: 34,
            views: 567,
            lastActivity: "hace 30 minutos",
            pinned: false,
            tags: ["build", "pve", "discusión"],
          },
          {
            id: 7,
            title: "Busco guild para raids",
            author: "NewPlayer",
            replies: 8,
            views: 123,
            lastActivity: "hace 1 hora",
            pinned: false,
            tags: ["guild", "raids", "busqueda"],
          },
        ],
      },
      {
        id: "creaciones",
        title: "CREACIONES",
        description: "Screenshots, videos y creaciones de jugadores",
        posts: [
          {
            id: 8,
            title: "Mi casa en el servidor - Tour completo",
            author: "BuilderPro",
            replies: 15,
            views: 345,
            lastActivity: "hace 2 horas",
            pinned: false,
            tags: ["construcción", "screenshot", "creativo"],
          },
        ],
      },
      {
        id: "sugerencias",
        title: "SUGERENCIAS",
        description: "Ideas y propuestas para mejorar el servidor",
        posts: [
          {
            id: 9,
            title: "Sugiero agregar sistema de mascotas",
            author: "PetLover",
            replies: 28,
            views: 456,
            lastActivity: "hace 4 horas",
            pinned: false,
            tags: ["sugerencia", "mascotas", "nueva-feature"],
          },
        ],
      },
    ],
  },
};

export const forumStats = {
  totalPosts: 1247,
  totalThreads: 89,
  totalMembers: 3456,
  onlineNow: 234,
  newestMember: "GamerNew2024",
};
